### ISSUE TITLE
UTF-8 Import an Export should be working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [skazsi/multiproperties#31]
```
What steps will reproduce the problem?
--------------------------------------
1. Importet an UTF-8 properties-file which contains russian translation for my 
keys
2. after importing the russian field in the multiproperties file shows 
"Ð¿ÑÐ¸Ð²ÐµÑ"

What is the expected output? What do you see instead?
------------------------------------------------------
I expect "привет" in the russian field like it is written in my UTF-8 
properties file.
Instead it shows "Ð¿ÑÐ¸Ð²ÐµÑ"


What version of the product are you using? On what operating system?
--------------------------------------------------------------------
1.2.0 on Windows 7

Please provide any additional information below.
------------------------------------------------
My use-case is that I send the property files of each language to a native 
speaker which translates this for me.
Sometimes I have to google-translate some filds for myself.
Therefore it would be very(!) important that it is possible to import AND 
export UTF-8 Files.

```

Original issue reported on code.google.com by `tl...@washtec.de` on 5 Dec 2012 at 4:49

Attachments:
- [Edit property record_2012-12-05_17-46-09.jpg](https://storage.googleapis.com/google-code-attachments/multiproperties/issue-31/comment-0/Edit property record_2012-12-05_17-46-09.jpg)
- [Edit property record_2012-12-05_17-46-36.jpg](https://storage.googleapis.com/google-code-attachments/multiproperties/issue-31/comment-0/Edit property record_2012-12-05_17-46-36.jpg)

**Comment by tazurc** [comment]
For UTF-8 encoding, please see the fork https://github.com/tazurc/multiproperties

**Comment by tazurc** [comment]
Code was merged and I deleted the fork...

**Comment by skazsi** [comment]
Yes, many thanks for the pull request. I'm working on it, and plan to release it soon.

**Comment by skazsi** [comment]
I'm done with the changes, mostly based on the pull request, however during the importing the encoding freely selectable, and not depending on the column's encoding setting. Thanks again for the pull request. Few days and I release it.
