### ISSUE TITLE
Eclipse update site (no repository found)

### ISSUE THREAD

**Issue by jansohn** [skazsi/multiproperties#39]
Seems like the update URL https://raw.githubusercontent.com/skazsi/multiproperties/master/hu.skzs.multiproperties.updatesite does not work anymore? Is there a working one available at the moment?

**Comment by Archangel1C** [comment]
Use the file site.xml:
https://raw.githubusercontent.com/skazsi/multiproperties/master/hu.skzs.multiproperties.updatesite/site.xml

**Comment by jansohn** [comment]
Thanks, seems to work!
