### ISSUE TITLE
Support Java 9+/11+ (deprecated/removed JavaEE APIs)

### ISSUE THREAD

**Issue by Archangel1C** [skazsi/multiproperties#41]
Hello,
when starting Eclipse with Java 9+, the Editor can't be opened, because the `java.xml.bind` module is deprecated and thus not added to the module path by default.

The JAXB APIs and dependencies should be packed with the plug-in (or how this is done with Eclipse plugins anyway).

Workaround:
With Java 9/10 you can add `--add-modules=java.xml.bind` to the eclipse.ini to activate the module and make the editor working again.
With Java 11+ the APIs are removed and thus can't be activated that way. You should be able to use `--module-path path/to/jaxb-api-jars-incl-dependencies` (maybe also the `--add-modules` parameter), but I did not get this to work, yet.

**Comment by skazsi** [comment]
Thanks for reporting. This project was a bit forgotten, but now I'm planning to fix this issue in the close future.
