### ISSUE TITLE
Editor doesn't seem to process changed resources

### ISSUE THREAD

**Issue by blutorange** [skazsi/multiproperties#46]
This plugin is great, but we keep running into deleted i18n keys when working as a team. There seems to be an issue for this already (#1), but it's from Google Code and it's still open - though the comments seem to suggest the issue is fixed. Can you shed some light on the current state of that issue?

The issue still seems to exist in the current version of the multiproperties editor:

* Open a multiproperties file
* Use git to pull from the repository (or switch to a different branch that has a different version of that file)
* The editor still shows the old file
* When you save the multiproperties file now, all changes from the pull are lost

If possible, it would be nice if the multiproperties editor could work the same way as Eclipse's Java source editor:

* If there are no unsaved changes, just update the editor with the new content
* If there are saved changes, let the user decide what to do (see screenshot below)

![image](https://user-images.githubusercontent.com/2456413/72155587-b231eb80-33b3-11ea-85d8-a781d4787019.png)

**Comment by skazsi** [comment]
Many thanks for your report and your kindness regarding the plugin in general. Unfortunately, the issue is still there, and I can hardly remember what challenge I run into years ago. At a certain point, it has been simply forgotten.

But, whenever someone reports something, it always gives me some motivation to do the requested features or bugs. I will check in the upcoming days...

**Comment by blutorange** [comment]
I can relate to that sentiment, I also get motivated when somebody else opens an issue. I'm glad you're still working on this. Take your time and enjoy the weekend : )

**Comment by skazsi** [comment]
Implemented in version 1.4.2.

**Comment by blutorange** [comment]
Thanks for the change. Just as feedback: I installed the new version and it's working fine - the editor recognizes that the file has changed and opens a prompt. (Perhaps no prompt would be neccessary when there are no unsaved changes - it could just replace the content of the editor - but it's fine as it is now).

**Comment by skazsi** [comment]
Thank you very much for your feedback. You might be right regarding no prompt for unsaved changes, I will consider it in a later release.
